# Generated by Django 4.2.1 on 2023-05-19 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compra_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Proveerdor',
            new_name='Proveedor',
        ),
    ]
